var time = +prompt("Введите время: ")

if (time == 12)
    alert("12 часов дня")
else if (time == 13)
    alert("час дня")
else if (time == 14)
    alert("2 часа дня")
else if (time == 15)
    alert("3 часа дня")
else if (time == 16)
    alert("4 часа дня")
else if (time == 17)
    alert('5 часо дня')
else if(time == 18)
    alert("6 часов вечера")
else if (time == 19)
    alert("7 часов вечера")
else if (time == 20)
    alert("8 часов вечера")
else if (time == 21)
    alert("9 часов вечера")
else if (time == 22)
    alert("10 часов вечера")
else if (time == 23)
    alert("11 часов вечера")
else if (time == 24)
    alert("12 часов ночи")
else if (time == 1)
    alert("час ночи")
else if (time == 2)
    alert("2 часа ночи")
else if (time == 3)
    alert("3 часа ночи")
else if (time == 4)
    alert("4 часа ночи")
else if (time == 5)
    alert("5 часов ночи")
else if (time == 6)
    alert("6 часов утра")
else if (time == 7)
    alert("7 часов утра")
else if (time == 9)
    alert("9 часов утра")
else if (time == 10)
    alert("10 часов утра")
else if (time == 11)
    alert("11 часов утра")